INSTANCE="xenial_sshd"
IMAGES=["ssh1", "ssh2", "ssh3"]
CLEAN_FILES=["ansible-hosts", "etc-hosts"]
VAGRANT_SSH_KEY="/home/follinge/projects/ansible-learning/.vagrant/machines/default/virtualbox/private_key"

task :default => [:playbook]

desc "test playbook"
task :playbook do
    sh "ansible-playbook -i inventory.ini provisioning/playbook.yml"
end
